query CurrentUser {
  currentUser{
    __typename
    id
    name
    fabrics {
      __typename
      id
      fabricType
      color
      size
      description
      name
      fabricPic
    }
    flosses {
      __typename
      id
      brand
      color
      amount
      flossPic
    }
    needles {
      __typename
      id
      needleType
      size
    }
    notions {
      __typename
      id
      name
      brand
      size
      description
      color
      notionPic
    }
    patterns {
      __typename
      id
      brand
      number
      patternFrontPic
      patternBackPic
    }
    yarns {
      __typename
      id
      yarnPic
      brand
      name
      lot
      color
      size
    }
  }
}
