query Patterns($search: SearchInput) {
  patterns(search: $search) {
    __typename
    count
    records {
      __typename
      id
      brand
      number
      patternBackPic
      patternFrontPic
    }
  }
}
